# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/azamath/Repositories/Galaxy_B13

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/azamath/Repositories/Galaxy_B13

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/azamath/Repositories/Galaxy_B13/CMakeFiles /Users/azamath/Repositories/Galaxy_B13//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/azamath/Repositories/Galaxy_B13/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Galaxy_B13

# Build rule for target.
Galaxy_B13: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Galaxy_B13
.PHONY : Galaxy_B13

# fast build rule for target.
Galaxy_B13/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/build
.PHONY : Galaxy_B13/fast

Client.o: Client.cpp.o
.PHONY : Client.o

# target to build an object file
Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/Client.cpp.o
.PHONY : Client.cpp.o

Client.i: Client.cpp.i
.PHONY : Client.i

# target to preprocess a source file
Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/Client.cpp.i
.PHONY : Client.cpp.i

Client.s: Client.cpp.s
.PHONY : Client.s

# target to generate assembly for a file
Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/Client.cpp.s
.PHONY : Client.cpp.s

MODULE.o: MODULE.cpp.o
.PHONY : MODULE.o

# target to build an object file
MODULE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/MODULE.cpp.o
.PHONY : MODULE.cpp.o

MODULE.i: MODULE.cpp.i
.PHONY : MODULE.i

# target to preprocess a source file
MODULE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/MODULE.cpp.i
.PHONY : MODULE.cpp.i

MODULE.s: MODULE.cpp.s
.PHONY : MODULE.s

# target to generate assembly for a file
MODULE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/MODULE.cpp.s
.PHONY : MODULE.cpp.s

aboutMenu.o: aboutMenu.cpp.o
.PHONY : aboutMenu.o

# target to build an object file
aboutMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/aboutMenu.cpp.o
.PHONY : aboutMenu.cpp.o

aboutMenu.i: aboutMenu.cpp.i
.PHONY : aboutMenu.i

# target to preprocess a source file
aboutMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/aboutMenu.cpp.i
.PHONY : aboutMenu.cpp.i

aboutMenu.s: aboutMenu.cpp.s
.PHONY : aboutMenu.s

# target to generate assembly for a file
aboutMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/aboutMenu.cpp.s
.PHONY : aboutMenu.cpp.s

buildRocket.o: buildRocket.cpp.o
.PHONY : buildRocket.o

# target to build an object file
buildRocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/buildRocket.cpp.o
.PHONY : buildRocket.cpp.o

buildRocket.i: buildRocket.cpp.i
.PHONY : buildRocket.i

# target to preprocess a source file
buildRocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/buildRocket.cpp.i
.PHONY : buildRocket.cpp.i

buildRocket.s: buildRocket.cpp.s
.PHONY : buildRocket.s

# target to generate assembly for a file
buildRocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/buildRocket.cpp.s
.PHONY : buildRocket.cpp.s

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/camera.cpp.s
.PHONY : camera.cpp.s

drawAll.o: drawAll.cpp.o
.PHONY : drawAll.o

# target to build an object file
drawAll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/drawAll.cpp.o
.PHONY : drawAll.cpp.o

drawAll.i: drawAll.cpp.i
.PHONY : drawAll.i

# target to preprocess a source file
drawAll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/drawAll.cpp.i
.PHONY : drawAll.cpp.i

drawAll.s: drawAll.cpp.s
.PHONY : drawAll.s

# target to generate assembly for a file
drawAll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/drawAll.cpp.s
.PHONY : drawAll.cpp.s

functions.o: functions.cpp.o
.PHONY : functions.o

# target to build an object file
functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/functions.cpp.o
.PHONY : functions.cpp.o

functions.i: functions.cpp.i
.PHONY : functions.i

# target to preprocess a source file
functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/functions.cpp.i
.PHONY : functions.cpp.i

functions.s: functions.cpp.s
.PHONY : functions.s

# target to generate assembly for a file
functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/functions.cpp.s
.PHONY : functions.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/main.cpp.s
.PHONY : main.cpp.s

optionsMenu.o: optionsMenu.cpp.o
.PHONY : optionsMenu.o

# target to build an object file
optionsMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/optionsMenu.cpp.o
.PHONY : optionsMenu.cpp.o

optionsMenu.i: optionsMenu.cpp.i
.PHONY : optionsMenu.i

# target to preprocess a source file
optionsMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/optionsMenu.cpp.i
.PHONY : optionsMenu.cpp.i

optionsMenu.s: optionsMenu.cpp.s
.PHONY : optionsMenu.s

# target to generate assembly for a file
optionsMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/optionsMenu.cpp.s
.PHONY : optionsMenu.cpp.s

parametrizationScreen.o: parametrizationScreen.cpp.o
.PHONY : parametrizationScreen.o

# target to build an object file
parametrizationScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/parametrizationScreen.cpp.o
.PHONY : parametrizationScreen.cpp.o

parametrizationScreen.i: parametrizationScreen.cpp.i
.PHONY : parametrizationScreen.i

# target to preprocess a source file
parametrizationScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/parametrizationScreen.cpp.i
.PHONY : parametrizationScreen.cpp.i

parametrizationScreen.s: parametrizationScreen.cpp.s
.PHONY : parametrizationScreen.s

# target to generate assembly for a file
parametrizationScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/parametrizationScreen.cpp.s
.PHONY : parametrizationScreen.cpp.s

spaceObjects.o: spaceObjects.cpp.o
.PHONY : spaceObjects.o

# target to build an object file
spaceObjects.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/spaceObjects.cpp.o
.PHONY : spaceObjects.cpp.o

spaceObjects.i: spaceObjects.cpp.i
.PHONY : spaceObjects.i

# target to preprocess a source file
spaceObjects.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/spaceObjects.cpp.i
.PHONY : spaceObjects.cpp.i

spaceObjects.s: spaceObjects.cpp.s
.PHONY : spaceObjects.s

# target to generate assembly for a file
spaceObjects.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/spaceObjects.cpp.s
.PHONY : spaceObjects.cpp.s

spaceShip.o: spaceShip.cpp.o
.PHONY : spaceShip.o

# target to build an object file
spaceShip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/spaceShip.cpp.o
.PHONY : spaceShip.cpp.o

spaceShip.i: spaceShip.cpp.i
.PHONY : spaceShip.i

# target to preprocess a source file
spaceShip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/spaceShip.cpp.i
.PHONY : spaceShip.cpp.i

spaceShip.s: spaceShip.cpp.s
.PHONY : spaceShip.s

# target to generate assembly for a file
spaceShip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/spaceShip.cpp.s
.PHONY : spaceShip.cpp.s

startMenu.o: startMenu.cpp.o
.PHONY : startMenu.o

# target to build an object file
startMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/startMenu.cpp.o
.PHONY : startMenu.cpp.o

startMenu.i: startMenu.cpp.i
.PHONY : startMenu.i

# target to preprocess a source file
startMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/startMenu.cpp.i
.PHONY : startMenu.cpp.i

startMenu.s: startMenu.cpp.s
.PHONY : startMenu.s

# target to generate assembly for a file
startMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxy_B13.dir/build.make CMakeFiles/Galaxy_B13.dir/startMenu.cpp.s
.PHONY : startMenu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Galaxy_B13"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... MODULE.o"
	@echo "... MODULE.i"
	@echo "... MODULE.s"
	@echo "... aboutMenu.o"
	@echo "... aboutMenu.i"
	@echo "... aboutMenu.s"
	@echo "... buildRocket.o"
	@echo "... buildRocket.i"
	@echo "... buildRocket.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... drawAll.o"
	@echo "... drawAll.i"
	@echo "... drawAll.s"
	@echo "... functions.o"
	@echo "... functions.i"
	@echo "... functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... optionsMenu.o"
	@echo "... optionsMenu.i"
	@echo "... optionsMenu.s"
	@echo "... parametrizationScreen.o"
	@echo "... parametrizationScreen.i"
	@echo "... parametrizationScreen.s"
	@echo "... spaceObjects.o"
	@echo "... spaceObjects.i"
	@echo "... spaceObjects.s"
	@echo "... spaceShip.o"
	@echo "... spaceShip.i"
	@echo "... spaceShip.s"
	@echo "... startMenu.o"
	@echo "... startMenu.i"
	@echo "... startMenu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

